//! Consultation d'un G-code produit (T066) : téléchargement (FR-044) et
//! statistiques (FR-043), post-traitement (`store_gcode` : fichier + stats +
//! vignettes), isolation inter-comptes (404, SC-008).

use std::sync::Arc;

use axum::body::{to_bytes, Body};
use axum::http::{header, Request, StatusCode};
use axum::response::Response;
use axum::Router;
use backend::adapters::files::FileStore;
use backend::adapters::storage::sqlite::SqliteStorage;
use backend::domain::repo::{NewJob, NewProject};
use backend::domain::{JobId, ProjectId, Storage, UserId};
use backend::http::routes::router;
use backend::http::state::AppState;
use serde_json::{json, Value};
use tower::ServiceExt;
use tower_sessions::{MemoryStore, SessionManagerLayer};

/// En-tête G-code Orca minimal (une vignette + quelques statistiques).
const SAMPLE_GCODE: &str = "\
; generated by OrcaSlicer
; thumbnail begin 2x2 16
; iVBORw0KGgoAAAAN
; SUhEUgAAAAI=
; thumbnail end
; total filament used [g] = 3.68
; total layers count = 42
; estimated printing time (normal mode) = 1h 2m 3s
G1 X0 Y0
G1 X10 Y10 E1.2
";

struct Harness {
    _dir: tempfile::TempDir,
    storage: Arc<SqliteStorage>,
    files: FileStore,
    app: Router,
}

async fn harness() -> Harness {
    let dir = tempfile::tempdir().unwrap();
    let url = format!("sqlite://{}", dir.path().join("gcodes.db").display());
    let storage = Arc::new(SqliteStorage::connect(&url).await.unwrap());
    let files = FileStore::new(dir.path().join("data"));
    let state = AppState::new(Arc::clone(&storage) as Arc<dyn Storage>, files.clone());
    let session_layer = SessionManagerLayer::new(MemoryStore::default()).with_secure(false);
    let app = router(state, session_layer);
    Harness {
        _dir: dir,
        storage,
        files,
        app,
    }
}

fn cookie(resp: &Response) -> String {
    resp.headers()
        .get(header::SET_COOKIE)
        .unwrap()
        .to_str()
        .unwrap()
        .split(';')
        .next()
        .unwrap()
        .to_string()
}

async fn register(app: &Router, email: &str) -> String {
    let resp = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/auth/register")
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(
                    json!({ "email": email, "password": "password123" }).to_string(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(resp.status(), StatusCode::CREATED);
    cookie(&resp)
}

async fn user_id(storage: &SqliteStorage, email: &str) -> UserId {
    storage
        .users()
        .find_by_email(email)
        .await
        .unwrap()
        .unwrap()
        .id
}

async fn make_job(storage: &SqliteStorage, owner: UserId) -> (ProjectId, JobId) {
    let project = storage
        .projects()
        .create(
            owner,
            NewProject {
                name: "P".into(),
                scene: json!({}),
                active_presets: json!({}),
                thumbnail_path: None,
            },
        )
        .await
        .unwrap();
    let job = storage
        .jobs()
        .enqueue(
            owner,
            NewJob {
                project_id: project.id,
                plate_index: 0,
                resolved_settings: json!({}),
            },
        )
        .await
        .unwrap();
    (project.id, job.id)
}

async fn body_bytes(resp: Response) -> Vec<u8> {
    to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap()
        .to_vec()
}

async fn get(app: &Router, uri: &str, session: &str) -> Response {
    app.clone()
        .oneshot(
            Request::builder()
                .method("GET")
                .uri(uri)
                .header(header::COOKIE, session)
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap()
}

#[tokio::test]
async fn downloads_the_stored_gcode_as_attachment() {
    let h = harness().await;
    let session = register(&h.app, "boss@test.local").await;
    let owner = user_id(&h.storage, "boss@test.local").await;
    let (_project, job) = make_job(&h.storage, owner).await;

    // Post-traitement : matérialise le résultat du job.
    let gcode = backend::gcode::store_gcode(&h.files, h.storage.gcodes(), owner, job, SAMPLE_GCODE)
        .await
        .unwrap();

    let resp = get(
        &h.app,
        &format!("/api/gcodes/{}/download", gcode.id),
        &session,
    )
    .await;
    assert_eq!(resp.status(), StatusCode::OK);
    let disposition = resp
        .headers()
        .get(header::CONTENT_DISPOSITION)
        .unwrap()
        .to_str()
        .unwrap()
        .to_string();
    assert!(disposition.contains("attachment"), "{disposition}");
    assert_eq!(body_bytes(resp).await, SAMPLE_GCODE.as_bytes());
}

#[tokio::test]
async fn returns_parsed_stats() {
    let h = harness().await;
    let session = register(&h.app, "boss@test.local").await;
    let owner = user_id(&h.storage, "boss@test.local").await;
    let (_project, job) = make_job(&h.storage, owner).await;
    let gcode = backend::gcode::store_gcode(&h.files, h.storage.gcodes(), owner, job, SAMPLE_GCODE)
        .await
        .unwrap();

    let resp = get(&h.app, &format!("/api/gcodes/{}/stats", gcode.id), &session).await;
    assert_eq!(resp.status(), StatusCode::OK);
    let stats: Value = serde_json::from_slice(&body_bytes(resp).await).unwrap();
    assert_eq!(stats["estimated_time_seconds"], 3723);
    assert_eq!(stats["total_filament_weight_g"], 3.68);
    assert_eq!(stats["layer_count"], 42);
}

#[tokio::test]
async fn store_gcode_persists_thumbnail() {
    let h = harness().await;
    let owner = {
        register(&h.app, "boss@test.local").await;
        user_id(&h.storage, "boss@test.local").await
    };
    let (_project, job) = make_job(&h.storage, owner).await;
    let gcode = backend::gcode::store_gcode(&h.files, h.storage.gcodes(), owner, job, SAMPLE_GCODE)
        .await
        .unwrap();

    let thumbs = gcode.thumbnails.as_array().unwrap();
    assert_eq!(thumbs.len(), 1);
    assert_eq!(thumbs[0]["width"], 2);
    assert_eq!(thumbs[0]["data"], "iVBORw0KGgoAAAANSUhEUgAAAAI=");
}

#[tokio::test]
async fn other_accounts_gcode_is_404() {
    let h = harness().await;
    register(&h.app, "alice@test.local").await;
    let alice = user_id(&h.storage, "alice@test.local").await;
    let (_project, job) = make_job(&h.storage, alice).await;
    let gcode = backend::gcode::store_gcode(&h.files, h.storage.gcodes(), alice, job, SAMPLE_GCODE)
        .await
        .unwrap();

    let bob = register(&h.app, "bob@test.local").await;
    for suffix in ["download", "stats"] {
        let resp = get(&h.app, &format!("/api/gcodes/{}/{suffix}", gcode.id), &bob).await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND, "{suffix}");
    }
}

#[tokio::test]
async fn malformed_id_is_404() {
    let h = harness().await;
    let session = register(&h.app, "boss@test.local").await;
    let resp = get(&h.app, "/api/gcodes/not-a-uuid/stats", &session).await;
    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
}
